version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis_cache
    expose:
      - 6379
  web:
    container_name: node_sequelize
    build: .
    links:
      - redis:redis
    environment:
      - REDIS_URL=redis://redis_cache
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
